### ISSUE TITLE
How to use, my menu ui don’t open

### ISSUE THREAD

**Issue by MadooxMc** [thodark/SkyblockUI#1]

**Comment by thodark** [comment]
hi, your ui cannot be opened because you did not enter the correct command
and you will also have to have the FormAPI plugin
Here is the link of FormAPI:https://github.com/jojoe77777/FormAPI
command is /sbui
I will add this command in the description
so sorry for this misunderstanding

Vào Th 4, 11 thg 8, 2021 vào lúc 17:34 MadooxMc ***@***.***>
đã viết:
